// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/callback.tsx";
import * as $1 from "./routes/index.tsx";
import * as $2 from "./routes/login.tsx";
import * as $$0 from "./islands/clean_url.tsx";
import * as $$1 from "./islands/main.tsx";

const manifest = {
  routes: {
    "./routes/callback.tsx": $0,
    "./routes/index.tsx": $1,
    "./routes/login.tsx": $2,
  },
  islands: {
    "./islands/clean_url.tsx": $$0,
    "./islands/main.tsx": $$1,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
